- .style.yapf
- CONTRIBUTING.md
- README.md
- cli/src/TODO
- cli/src/breakpoint_utils.py
- cli/src/cli.py
- cli/src/cli_common_arguments.py
- cli/src/cli_services.py
- cli/src/command_utils.py
- cli/src/delete_snapshots_command.py
- cli/src/exceptions.py
- cli/src/firebase_management_rest_service.py
- cli/src/firebase_rtdb_rest_service.py
- cli/src/firebase_types.py
- cli/src/format_utils.py
- cli/src/gcloud_cli_service.py
- cli/src/get_snapshot_command.py
- cli/src/http_service.py
- cli/src/init_command.py
- cli/src/list_debuggees_command.py
- cli/src/list_snapshots_command.py
- cli/src/permissions_rest_service.py
- cli/src/set_snapshot_command.py
- cli/src/snapshot_parser.py
- cli/src/status_message.py
- cli/src/user_input.py
- cli/src/user_output.py
- pylintrc
This is the initial commit containing the CLI code, README.md and formatting and linting config files.
> Initial code check in.

- README.md
Some fixes and improvements for the README.
> Some fixes and improvments for the README

- cli/src/cli_services.py
This improves the link provided in the check configuration message
presented to the user.
> Small tweak to improve link to readme.

- cli/src/COMMAND_REFERENCE.md
- cli/src/list_snapshots_command.py
Add support for the `all-users` argument to the list_snapshots command.
Fixes #4
> Add `all-users` option for list_snapshots

- README.md
Rework the format to be in Symptom/Resolution division for each issue.
> Reformat troubleshooting

- cli/data_formatter.py
- cli_tests/test_data_formatter.py
Provide a default value of 0 to max() in Dataformatter.build_table().
Fixes #32
> Fix list_snapshots when no snapshots to display.

- snapshot_dbg_cli/cli_run.py
- snapshot_dbg_cli/cli_services.py
- snapshot_dbg_cli/get_snapshot_command.py
- snapshot_dbg_cli_tests/test_get_snapshot_command.py
Create unit test covering the get_snapshot command.
> Add get_snapshot unittest

- snapshot_dbg_cli/list_snapshots_command.py
- snapshot_dbg_cli_tests/test_list_snapshots_command.py
Add unit tests covering list_snapshots command.
> Add unit tests covering list_snapshots command

- snapshot_dbg_cli/init_command.py
- snapshot_dbg_cli_tests/test_init_command.py
Add unit tests covering the init command.
> Add unit tests covering the init command.

- snapshot_dbg_cli/breakpoint_utils.py
- snapshot_dbg_cli/set_snapshot_command.py
- snapshot_dbg_cli_tests/test_set_snapshot_command.py
Add unit tests covering set_snapshot command.
> Add unit tests covering set_snapshot command.

- snapshot_dbg_cli/cli_services.py
- snapshot_dbg_cli_tests/test_cli_services.py
> Create cli_services unittest

- snapshot_dbg_cli/breakpoint_utils.py
- snapshot_dbg_cli_tests/test_breakpoint_utils.py
> normalize_breakpoints ensures breakpoint is a dict.

- snapshot_dbg_cli/__init__.py
- Contains fix to robustify breakpoint processing.
- Contains fix to include function arguments in `get_snapshot` output
- Contains README update to reflect new Debuggee ID format.
> Bump version to 0.1.1

- README.md
- snapshot_dbg_cli/cli_version.py
- snapshot_dbg_cli_tests/test_init.py
This is a documentation release only.
* Update README with Java and Python agent information.
> chore: release 0.2.1

- snapshot_dbg_cli/cli_services.py
- snapshot_dbg_cli/firebase_rtdb_rest_service.py
- snapshot_dbg_cli/http_service.py
- snapshot_dbg_cli/init_command.py
- snapshot_dbg_cli_tests/test_firebase_rtdb_rest_service.py
- snapshot_dbg_cli_tests/test_http_service.py
- snapshot_dbg_cli_tests/test_init_command.py
> fix: Remove sleep from init command

- README.md
- snapshot_dbg_cli/COMMAND_REFERENCE.md
- snapshot_dbg_cli/cli_run.py
- snapshot_dbg_cli/debuggee_utils.py
- snapshot_dbg_cli/delete_debuggees_command.py
- snapshot_dbg_cli/list_debuggees_command.py
- snapshot_dbg_cli/snapshot_debugger_rtdb_service.py
- snapshot_dbg_cli/snapshot_debugger_schema.py
- snapshot_dbg_cli/time_utils.py
- snapshot_dbg_cli_tests/test_cli_run.py
- snapshot_dbg_cli_tests/test_delete_debuggees_command.py
- snapshot_dbg_cli_tests/test_snapshot_debugger_rtdb_service.py
- snapshot_dbg_cli_tests/test_snapshot_debugger_schema.py
> feat: Add delete debuggees command.

- snapshot_dbg_cli/cli_version.py
- snapshot_dbg_cli_tests/test_init.py
This is a documentation update only.
* The main README has updates about the limitations and a link to the samples directory.
> chore: Release 0.3.1

- snapshot_dbg_cli/cli_version.py
- snapshot_dbg_cli_tests/test_init.py
This is a documentation update only.
* Moved some of the documentation from the main README into more focused individual doc files.
> chore: Release 0.3.2

- README.md
> docs: Clarify support period

- .github/workflows/scorecard.yml
Default configuration.  Installing following instructions at https://github.com/ossf/scorecard-action#installation
> chore: Create scorecard.yml

- snapshot_dbg_extension/package.json
This allows VS Code to set breakpoints in PHP files
> Adds PHP support to the VS Code Extension

- README.md
This provides the documentation for #154
> docs: Document archival status
