README.md, cli/src/cli_common_arguments.py
Add support for specifying the `debuggee-id` and `database-url`
arguments via environment variables. When both are specified the value
from the command line takes precedence.
Closes #11
=> Support specifying some arguments via environment

README.md, cli/src/cli_common_arguments.py, cli/src/cli_services.py, cli/src/delete_snapshots_command.py, cli/src/firebase_management_rest_service.py, cli/src/firebase_types.py, cli/src/get_snapshot_command.py, cli/src/init_command.py, cli/src/list_debuggees_command.py, cli/src/list_snapshots_command.py, cli/src/set_snapshot_command.py
The CLI will now test for a configured Snapshot Debugger database instance of `{project_id}-cdbg`.  Failing that it will then test the default Firebase RTDB instance to see if it has been configured for use by the Snapshot Debugger. This removes the need for the `--use-default-rtdb` argument from all commands other than the `init` command.
The `--database-url` override option remains when needed to provide a specific URL to use.
Fixes #5
=> Autodetect if the default RTDB should be used

cli/src/format_utils.py, cli/src/user_output.py
Ensure all users messages go to stderr, while stdout is reserved for
JSON formatted messages.
Fixes #2.
=> Clean up user output for stdout/stderr

README.md
Added a note to the troubleshooting section of the README about how to
view the RTDB instance in the Firebase Console if it is not showing up
by default.
Fixes #25
=> Add note to README for viewing the RTDB in console.

pylintrc, snapshot_dbg_cli/data_formatter.py
- Sync with latest https://google.github.io/styleguide/pylintrc.
- Fix warning in data_formatter module, use generator instead of list
comprehension.
Fixes #49
=> Address warnings with newer version of pylint.

.gitignore, README.md, setup.cfg, setup.py, snapshot_dbg_cli/COMMAND_REFERENCE.md
Add setup.cfg and associated required changes to allow packaging the CLI.
This has been tested using TestPyPI.
- https://test.pypi.org/project/snapshot-dbg-cli/0.0.1/
- python3 -m pip install -i https://test.pypi.org/simple/ snapshot-dbg-cli
Fixes #60
=> Add build/packaging support.

snapshot_dbg_cli/snapshot_parser.py, snapshot_dbg_cli_tests/test_snapshot_parser.py
This change ensures the `get_snapshot` command will display the captured
data for variables classified as `arguments` for functions in the call
stack.
Fixes #61
=> Include function `arguments` when parsing locals.

README.md
Debuggee IDs are now formated like the following: `d-14fde481`, so the
examples in the README have been updated to reflect this.
Fixes #65
=> Update debuggee ID examples in the README.

snapshot_dbg_cli/COMMAND_REFERENCE.md, snapshot_dbg_cli/cli_run.py, snapshot_dbg_cli/delete_breakpoints.py, snapshot_dbg_cli/delete_logpoints_command.py, snapshot_dbg_cli/delete_snapshots_command.py, snapshot_dbg_cli_tests/test_cli_run.py, snapshot_dbg_cli_tests/test_delete_logpoints_command.py, snapshot_dbg_cli_tests/test_delete_snapshots_command.py
To note, this change is dependent on #70, requiring the changes to [breakpoint_utils.py](https://github.com/GoogleCloudPlatform/snapshot-debugger/pull/70/files#diff-fbb1e002e858866b5dcb4f8fef9a8982d0ee60361cbdc74dd862aff0402abd62) and [snapshot_debugger_rtdb_service.py](https://github.com/GoogleCloudPlatform/snapshot-debugger/pull/70/files#diff-ef8744b8574033c0cdbd967ee979c8d7d8e1d498923cbe52e908cb01ab3e7863).
=> feat: Add `delete_logpoints` command.

snapshot_dbg_cli/__init__.py, snapshot_dbg_cli/cli_version.py, snapshot_dbg_cli_tests/test_init.py
This is a minor version bump to account for the support of the logpoint commands.
=> chore: Bump version to 0.2.0.

snapshot_dbg_cli/cli_version.py, snapshot_dbg_cli_tests/test_init.py
This is a documentation update only.
* Update README with Java and Python agent information.
* Contains a small doc fix to 0.2.1 which was intended to be released with the Java and Python agent information.
=> chore: release 0.2.2

samples/java/appengine-java11/simple-server/README.md, samples/java/appengine-java11/simple-server/app.yaml
This will help avoid issues with running through the examples, as if
this is the first deploy of an app engine app on the project it will
fail, since the first deploy must be the `default` service.
=> chore: Remove service simple server

snapshot_dbg_cli/COMMAND_REFERENCE.md, snapshot_dbg_cli/breakpoint_utils.py, snapshot_dbg_cli/debuggee_utils.py, snapshot_dbg_cli/list_debuggees_command.py, snapshot_dbg_cli/snapshot_debugger_rtdb_service.py, snapshot_dbg_cli/time_utils.py, snapshot_dbg_cli_tests/test_breakpoint_utils.py, snapshot_dbg_cli_tests/test_debuggee_utils.py, snapshot_dbg_cli_tests/test_list_debuggees_command.py, snapshot_dbg_cli_tests/test_snapshot_debugger_rtdb_service.py, snapshot_dbg_cli_tests/test_time_utils.py
In support of https://github.com/GoogleCloudPlatform/snapshot-debugger/issues/76 the `list_debuggees` command now:
- Shows only active debuggees by default
- Supports a `--include-inactive` flag
- Sorts the output with the most recently active debuggees being shown
first.
=> feat: list_debuggees supports active debuggees

samples/node-js/gce/app.js, samples/node-js/gce/package.json
This sample app will show users how to set up the snapshot debugger node.js agent in GCE.
Follow-up CLs will be created for the startup script and the README that will include instructions.  The startup script will download the app from this repo, however, so this must be checked in first.
=> docs: Add sample Node.js GCE app

snapshot_dbg_cli/cli_version.py, snapshot_dbg_cli_tests/test_init.py
This is a minor version bump to account for active debuggee support.
* `list_debuggees` now supports the `--include-inactive` option and by default will only show active debuggees. In addition is has two new output columns, `Status` and `Last Active`.
* A new command `delete_debuggees` has been added, which by default it will only delete stale debuggees.
* An improvement for the `init` command is also included, which reduces the chances of it failing attempting to initialize the DB instance after creating it.
=> chore: release 0.3.0

snapshot_dbg_cli/set_snapshot_command.py, snapshot_dbg_cli_tests/test_set_snapshot_command.py
The CLI now explicitly sets the `action` field to `CAPTURE` in the breakpoint when setting a snapshot.
=> chore: set_snaphsot now explicitly sets `action`

snapshot_dbg_cli/cli_version.py, snapshot_dbg_cli_tests/test_init.py
- set_snapshot command now explicitly sets `action` field
- Main README updates
- Note about Java 8 not being supported now removed (it is now supported).
- Clarification added to Support Period
=> chore: Release 0.3.3

README.md, docs/SCHEMA.md
Add documentation for the DB schema used by the Snapshot Debugger.
This addresses #125
=> docs: Document the DB schema

snapshot_dbg_cli/cli_version.py
Removed the use of str.removeprefix(), which was added in Python 3.9 to allow the CLI to run on older versions of Python.
=> fix: Remove use of str.removeprefix

snapshot_dbg_cli_tests/test_delete_debuggees_command.py, snapshot_dbg_cli_tests/test_list_debuggees_command.py
The `args` property was added to `call_args` in Python 3.8
(https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock.call_args)
We want to be able to run the unit tests earlier versions an so must avoid using it.
=> Don't rely on call_args.args in unit tests.

snapshot_dbg_cli/cli_version.py, snapshot_dbg_cli_tests/test_init.py
- Removes the use of str.removeprefix, allowing the CLI to run on Python versions prior to 3.9
=> chore: Release 0.3.4

snapshot_dbg_extension/package.json, snapshot_dbg_extension/src/adapter.ts, snapshot_dbg_extension/src/breakpointManager.ts
- Avoid syncing active breakpoints from the backend while the setBreakPointsRequest is active.
- Use a copy of the setBreakPointsRequest input breakpoints and provide copies of the breakpoints in the corresponding response.
=> chore: VS Code extension breakpoint syncing tweaks

snapshot_dbg_extension/package.json, snapshot_dbg_extension/src/adapter.ts
The connection timeout is currently hardcoded to 2 seconds.  It is likely that this is not going to work in all situations, so I'm adding a configuration knob to allow the user to set whatever timeout they'd like.
Depending on feedback, the default timeout may be increased as well.  The balance is that if the extension is attempting to discover the database, increases in timeouts will result in slower extension startup.
This PR is related to #135
=> feat: Add ability to configure connection timeout

pylintrc
Use fully qualified exception names in overgeneral-exceptions option.
This fixes the following warning:
```
pylint: Command line or configuration file:1: UserWarning: Specifying exception names in the overgeneral-exceptions option without module name is deprecated and support for it will be removed in pylint 3.0. Use fully qualified name (maybe 'builtins.BaseException' ?) instead.
```
=> chore: Update pylintrc to avoid warning

snapshot_dbg_cli/cli_version.py, snapshot_dbg_cli_tests/test_init.py
The CLI now supports creating the Firebase RTDB in different regions, as listed in
https://firebase.google.com/docs/projects/locations#rtdb-locations. This can be specfied via the `--location` parameter in the `init` command.
=> chore: Release CLI 0.3.5

snapshot_dbg_cli/cli_version.py, snapshot_dbg_cli_tests/test_init.py
No functional changes, need a new release to update the README on pypi.
=> chore: Release CLI 0.3.6

snapshot_dbg_extension/README.md
=> docs: Improve VS Code extension documentation
